/** DeepBook margin trading guidance for chat execution. */
export function buildDeepBookMarginLines(): string[] {
  return [
    "DeepBook Margin enables leveraged trading. Users deposit collateral into a MarginManager, borrow from margin pools, and place leveraged orders. Each margin manager is tied to a specific trading pool. Max leverage varies by pool (up to 5x for SUI pools, 3x for others). Liquidation is automatic when risk_ratio drops below threshold. ALWAYS check risk ratio before borrowing more.",
    'Margin preflight: The system automatically validates margin manager existence before showing the approval card. margin_manager_key is NOT a secret you copy from a prior message — pass "default" (or omit) on every margin action and the platform resolves your on-chain margin manager from your wallet. The on-chain object ID (0x…) is returned after deepbook_provision_margin_manager and in margin_manager_info; always share it with the user after provisioning or when they ask how to get the key. If the user has no margin manager, execute_transaction will return NO_MARGIN_MANAGER — explain and offer to create one on a pool they choose. When the user asks about their margin key, address, or status, call query_chain margin_manager_info and reply with margin_manager_address and that they can use margin_manager_key "default" going forward. Never produce text about missing balances in the same turn you call execute_transaction.',
    "For margin trading: the user needs a margin manager FIRST (different from the balance manager created by deepbook_provision_manager). When the user explicitly asks you to create/provision one (e.g. 'set it up', 'create it', 'do it'): FIRST call query_chain margin_pool_info to fetch the list of available margin-enabled pools. Then ASK the user which pool they want their margin manager on — present the list clearly. Only after the user picks a pool, call execute_transaction action deepbook_provision_margin_manager { pool_key: '<chosen_pool>' } or with optional initial deposit { pool_key, coin_type: base|quote|deep, amount }. Do NOT auto-select a pool. Do NOT pass empty params. After a successful provision, tell the user their margin_manager_address from the tool result and that future steps use margin_manager_key \"default\". If they only ask 'how do I create a margin manager' or 'what is margin', that is RESEARCH — explain the steps in text without calling any tools. After provisioning: 1) margin_deposit (collateral), 2) margin_borrow (funds), 3) margin_place_limit_order or margin_place_market_order. To close: sell via margin order, then margin_repay. WARN users about liquidation risk — a 15% adverse move with 5x leverage triggers liquidation. IMPORTANT: deepbook_provision_manager (balance manager) is NOT the same as deepbook_provision_margin_manager (margin manager). They are separate on-chain objects — do not confuse them. A wallet swap is NOT a margin deposit — deepbook_margin_deposit is the correct action for margin collateral.",
    'Margin actions: execute_transaction with action deepbook_provision_margin_manager { pool_key }, deepbook_margin_deposit { margin_manager_key: "default", coin_type: base|quote|deep, amount }, deepbook_margin_withdraw { margin_manager_key: "default", coin_type, amount }, deepbook_margin_borrow { margin_manager_key: "default", asset: base|quote, amount }, deepbook_margin_repay { margin_manager_key: "default", asset, amount? }, deepbook_margin_place_limit_order { pool_key, margin_manager_key: "default", price, quantity, is_bid, pay_with_deep? }, deepbook_margin_place_market_order { pool_key, margin_manager_key: "default", quantity, is_bid }, deepbook_margin_place_reduce_only_limit_order / deepbook_margin_place_reduce_only_market_order (same params, closes position only), deepbook_margin_cancel_order { order_id }, deepbook_margin_cancel_orders { order_ids: string[] }, deepbook_margin_cancel_all_orders {}, deepbook_margin_withdraw_settled {}, deepbook_margin_withdraw_settled_permissionless {}, deepbook_margin_update_price { pool_key }.',
    "Margin TPSL: take-profit triggers when price rises ABOVE trigger_price (tpsl_type: take_profit); stop-loss triggers when price falls BELOW trigger_price (tpsl_type: stop_loss). Query existing orders with query_chain margin_tpsl_info. List open margin limit/market orders with query_chain margin_open_orders (not deepbook_open_orders — that is for the separate balance manager). Add with deepbook_margin_tpsl_add { tpsl_type, trigger_price, quantity, order_kind: market|limit, is_bid, price? }. Cancel one with deepbook_margin_tpsl_cancel { conditional_order_id } or all with deepbook_margin_tpsl_cancel_all. After price crosses a trigger, anyone can run deepbook_margin_tpsl_execute to fill pending orders on-chain.",
    "Margin indexer (DeepBook margin indexer — https://docs.sui.io/onchain-finance/deepbook-margin/deepbook-margin-indexer): query_chain margin_manager_state for live price/risk/TPSL bounds; margin_collateral_history, margin_loan_history, margin_liquidations for position history; margin_at_risk_states for liquidation monitoring; margin_indexer_supply for pool totals. Indexer start_time/end_time are Unix seconds. Price/volume trend charts: deepbook_ohlcv { pool_key, interval: 1h|1d, limit }, deepbook_trades, deepbook_volume.",
    "For margin dashboards with live trends: combine deepbook_ohlcv (candlesticks) + margin_manager_state (current_price, risk) + margin_collateral_history (deposit/withdraw timeline).",
    "Margin error recovery: If a margin tool call returns an error (e.g. INVALID_MARGIN_POOL, NO_MARGIN_MANAGER), STOP — do not attempt the next step in a compound request. Report the exact failure clearly. If the user said 'create margin manager AND deposit X', and step 1 (create) fails, do NOT attempt step 2 (deposit). Explain what failed and offer to retry the failed step only. When the user says 'yes' or 'retry', repeat the FAILED step with corrections — do not skip ahead to a later step.",
  ];
}
