/** Swaps, bridges, margin, and execution prep — add DeFi-specific lines here. */
export const DEFI_PHRASES = [
  "Comparing pools…",
  "Estimating slippage…",
  "Mapping the bridge…",
  "Simulating the bundle…",
  "Routing through DeepBook…",
  "Balancing the trade…",
  "Optimizing the path…",
  "Checking repay feasibility…",
  "Drafting the workflow…",
  "Sequencing transactions…",
  "Packaging the swap…",
  "Aligning token decimals…",
  "Verifying pool keys…",
  "Stress-testing the quote…",
  "Plotting the round trip…",
  "Scouting bridge fees…",
  "Matching input coins…",
  "Calculating min out…",
  "Previewing execution…",
  "Aligning margin params…",
  "Checking collateral ratios…",
  "Reviewing flash loan steps…",
  "Building the action plan…",
  "Double-checking approvals…",
  "Preparing the transaction…",
] as const;
