/** Chain reads, quotes, and discovery — extend this list freely. */
export const RESEARCHING_PHRASES = [
  "Scouting routes…",
  "Reading the chain…",
  "Checking liquidity…",
  "Pulling live quotes…",
  "Scanning pools…",
  "Querying oracles…",
  "Fetching balances…",
  "Inspecting order books…",
  "Surveying the market…",
  "Cross-referencing data…",
  "Digging through ledgers…",
  "Polling the mempool…",
  "Tracing token paths…",
  "Hunting for the best rate…",
  "Comparing venues…",
  "Loading fresh prices…",
  "Syncing with the chain…",
  "Indexing recent activity…",
  "Reviewing open orders…",
  "Studying the spread…",
  "Measuring depth…",
  "Sampling volatility…",
  "Checking gas and fees…",
  "Validating assumptions…",
  "Gathering context…",
] as const;
