/** General cognition — add more strings to this array anytime. */
export const THINKING_PHRASES = [
  "Ruminating…",
  "Pondering…",
  "Thinking…",
  "Marinating on it…",
  "Turning it over…",
  "Connecting the dots…",
  "Letting it simmer…",
  "Weighing the options…",
  "Piecing it together…",
  "Following the thread…",
  "Reading between the lines…",
  "Untangling the knot…",
  "Sorting the pieces…",
  "Mapping the logic…",
  "Tracing the path…",
  "Gathering thoughts…",
  "Synthesizing…",
  "Reasoning through it…",
  "Working the problem…",
  "Chewing on it…",
  "Mulling it over…",
  "Brainstorming…",
  "Connecting neurons…",
  "Spinning up ideas…",
  "Calibrating intuition…",
] as const;
