import { formatRadiantClientApiGuideForPrompt } from "../../../projects/radiant-client-api-catalog.js";

export function buildArtifactDefiUiLines(): string[] {
  return [
    "For DeepBook swap/DEX UIs you generate from scratch: split into components (e.g. SwapForm.tsx), compose in app/page.tsx, import { swapQuote, poolInfo, resolveSwapSide } from \"../lib/radiant-client\". Import \"../lib/radiant-agent-runtime\" from app/page.tsx (side effect). REQUIRED — LIVE QUOTES (no manual quote button): fetch quotes automatically when the user types an amount or changes from/to tokens. Use a debounced useEffect (~250ms) on [amount, poolKey, fromToken, toToken]: const side = resolveSwapSide(poolKey, fromToken); const q = await swapQuote({ pool_key: poolKey, amount: Number(amount), side }); setQuote(q). Clear quote when amount is empty/invalid. Display quote.output_amount_display (alias estimated_out_display), price, and a loading state — NEVER add a separate 'Get quote' / 'Fetch quote' button. poolInfo(poolKey) on mount — never process.env in generated code. ONLY the Swap/Execute button calls window.__radiantAgent.execute('swap', { pool_key, amount: Number(amount), side, estimated_out_display: quote?.output_amount_display ?? quote?.estimated_out_display }, { animate: false }); the platform runtime shows an in-app confirm modal automatically — never handle approval_required manually. Wire the same execute pattern for flash_loan, stake, unstake, governance, and order actions. Never call execute_transaction from generated app code.",
    formatRadiantClientApiGuideForPrompt(),
    'CRITICAL — data-radiant-id attributes: Every interactive element MUST have a data-radiant-id attribute so the agent can visually drive the UI in real time. Use descriptive IDs matching the action schema: <input data-radiant-id="amount-in" />, <input data-radiant-id="amount" />, <select data-radiant-id="token-from" />, <select data-radiant-id="token-to" />, <select data-radiant-id="side" />, <button data-radiant-id="swap-submit" />, <button data-radiant-id="approve-button" />. For non-swap apps use action-specific IDs: <input data-radiant-id="weight" />, <input data-radiant-id="sets" />, <button data-radiant-id="log-submit" />. Without these, the agent cannot animate or set fields visually.',
    "CRITICAL — Action manifest (lib/radiant-actions.ts): Every generated app that exposes actions the agent can perform MUST include a lib/radiant-actions.ts file declaring the app's action schema. This file is parsed by the platform to make actions discoverable. Format: export const actions = [{ name: 'log_workout', description: 'Log a completed workout', params: [{ name: 'workout_name', type: 'string', required: true }, { name: 'date', type: 'string', required: true }] }]; Use lowercase snake_case for action names. Include all interactive actions the app supports.",
    "CRITICAL — Agent handler registration: Every generated app MUST register handlers via window.__radiantAgent.register on mount. Handlers receive (params, ctx) where ctx provides: ctx.setField(radiantId, value) to visually fill an input; ctx.delay(ms) to pause so the user sees each step; ctx.highlight(radiantId) to flash focus on an element; ctx.executeAction(action, params) to call the backend API (only for on-chain actions); ctx.dispatchEvent(name, detail) to notify React state. The handler MUST drive the UI step by step: set fields with delays between them, highlight the submit button, then either call ctx.executeAction (for DeFi) or click the submit button (for app-local). Example for DeFi: window.__radiantAgent.register('swap', async (params, ctx) => { ctx.setField('amount-in', params.amount); await ctx.delay(400); ctx.highlight('swap-submit', 'agent-clicking'); await ctx.delay(500); return await ctx.executeAction('swap', params); }); Example for app-local: window.__radiantAgent.register('log_workout', async (params, ctx) => { ctx.setField('workout-name', params.workout_name); await ctx.delay(400); ctx.setField('date', params.date); await ctx.delay(400); ctx.highlight('log-submit', 'agent-clicking'); await ctx.delay(500); document.querySelector('[data-radiant-id=\"log-submit\"]')?.click(); return { status: 'executed', digest: '', explorer_url: null, result: {} }; });",
    "CRITICAL — React state sync: Generated apps should listen for radiant-agent-set-field custom events to update React state when the agent drives the UI: useEffect(() => { const handler = (e) => { const { field, value } = e.detail; if (field === 'amount') setAmount(value); if (field === 'side') setSide(value); }; window.addEventListener('radiant-agent-set-field', handler); return () => window.removeEventListener('radiant-agent-set-field', handler); }, []);",
    "Use react / react-dom / react-router-dom / lucide-react ONLY — never import chart.js, recharts, framer-motion, date-fns, or ANY other third-party npm package. For price/OHLCV charts import { OhlcvAreaChart, AreaChart, Sparkline, extractCloseSeries } from \"../lib/radiant-charts\" — pass deepbookOhlcv().candles to OhlcvAreaChart. Do NOT hand-roll SVG chart paths. Prefer lucide-react for icons. globals in app/globals.css.",
  ];
}
